### ISSUE TITLE
Compilation Warnings - no model visible in OpenSCAD

### ISSUE THREAD

**Issue by StigZord** [dereknheiley/dactyl-manuform-tight#2]
I have followed design generation steps, but can't correctly open them in OpenSCAD.

Here is what happens:

I run `lein auto generate`
I get the message: `auto> Complete`
Open OpenSCAD select any of the `.scad` files, for example `switch-plates-right.scad`

In the OpenSCAD console I see following warnings:
```
Compiling design (CSG Tree generation)...
[WARNING: Ignoring unknown variable 'scad' in file switch-plates-right.scad, line 67466]
[WARNING: Ignoring unknown variable 'clj' in file switch-plates-right.scad, line 67466]
[WARNING: Ignoring unknown variable 'cut' in file switch-plates-right.scad, line 67466]
[WARNING: undefined operation (undefined / undefined) in file switch-plates-right.scad, line 67466]
[WARNING: undefined operation (undefined - undefined) in file switch-plates-right.scad, line 67466
Compiling design (CSG Products generation)...
Geometries in cache: 4328
Geometry cache size in bytes: 4033368
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
WARNING: Normalized tree is growing past 200000 elements. Aborting normalization.  
WARNING: CSG normalization resulted in an empty tree 
Normalized tree has 0 elements!
Compile and preview finished.
Total rendering time: 0:00:02.179
``` 

and there isn't any model present in the preview window.

Am I doing something wrong?

**Comment by dereknheiley** [comment]
This is the important part.
`WARNING: Normalized tree is growing past 200000 elements. Aborting normalization.`
`WARNING: CSG normalization resulted in an empty tree` 
`Normalized tree has 0 elements!`

I take a pretty lazy approach to performance tuning. Which is to say, i don't for casual things.

I got around this issue by increasing these values in the scad program preferences.
`NOTE: you will probably have to increase OpenSCAD params:`
`Turn off rendering at ~10,000,000` <----- this one needs to be higher, scad is giving up because it's currently at 200k
`CGAL cache size ~8000mb`
`PolySet cache size ~8000mb`
